# Generated by Django 5.1.6 on 2025-02-11 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-created_at'], 'verbose_name': 'business', 'verbose_name_plural': 'businesses'},
        ),
        migrations.AlterField(
            model_name='business',
            name='booking_url',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
