# Generated by Django 5.1.6 on 2025-02-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_business_options_alter_business_booking_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='calendar_id',
            field=models.CharField(blank=True, help_text='Google Calendar ID for this business', max_length=255, null=True),
        ),
    ]
