# Generated by Django 5.1.6 on 2025-02-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
